"""create documents table

Revision ID: a1ee10b838e2
Revises: 7933d4808a2c
Create Date: 2026-08-31 11:02:06.560463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ee10b838e2'
down_revision: Union[str, Sequence[str], None] = '7933d4808a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'documents',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('source_id', sa.Integer(), nullable=False),
		sa.Column('source_url', sa.String(), nullable=False),
		sa.Column('canonical_url', sa.String(), nullable=True),
		sa.Column('title', sa.String(), nullable=True),
		sa.Column('description', sa.Text(), nullable=True),
		sa.Column('author', sa.String(), nullable=True),
		sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
		sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
		sa.Column('content', sa.Text(), nullable=False),
		sa.Column('content_type', sa.String(), nullable=True),
		sa.Column('http_status', sa.Integer(), nullable=True),
		sa.Column('extraction_status', sa.String(), nullable=False),
		sa.Column('meta', sa.JSON(), nullable=False),
		sa.Column('fingerprint', sa.String(), nullable=True),
		sa.Column('fingerprint_version', sa.String(), nullable=True),
		sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
		sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
		sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
		sa.PrimaryKeyConstraint('id'),
		sa.UniqueConstraint('fingerprint')
	)
	op.create_index('ix_documents_fingerprint', 'documents', ['fingerprint'], unique=False)
	op.create_index('ix_documents_source_id', 'documents', ['source_id'], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index('ix_documents_source_id', table_name='documents')
	op.drop_index('ix_documents_fingerprint', table_name='documents')
	op.drop_table('documents')
	# ### end Alembic commands ###
